### PR TITLE
Issue #1110 - workspaceFolder server capability

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by angelozerr** [comment]
Thanks @mickaelistria!  Your PR looks good but it seems that we have a bug in telemetry test which breaks the build https://ci.eclipse.org/lemminx/blue/organizations/jenkins/lemminx/detail/PR-1111/1/pipeline#step-30-log-388

I'm very busy now, but as soon as I will find time, I will investigate the problem.

**Comment by mickaelistria** [comment]
The submitted code was causing the NPE. I could reproduce it locally and fixed it. Patch can now be reviewed without further concerns.

**Comment by mickaelistria** [comment]
I could successfully test it (with latest snapshots of wild web developer, m2e, lemminx-maven...) and could verify that it works as expected and does fix #1110 / https://github.com/eclipse-m2e/m2e-core/issues/287

**Comment by angelozerr** [comment]
Thanks @mickaelistria !

**Comment by mickaelistria** [comment]
Thanks @angelozerr

**Pull request merged**
