### PR TITLE
Improve ETagRequired error range

### LINKED ISSUE #876: Improve ETagRequired error range
Given this XML file:

```xml
<foo>
  <bar></
</foo>
```

We have that:

image

Although the ETagRequired error range should highlight the start tag element:

### PR DESCRIPTION
**Pull request by angelozerr**
Improve ETagRequired error range

Fixes #876

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
My code requires to be cleaned and I need to add some tests again, but I think we can start to play with it.

Basicly, this PR improves error range for diagnostic. For instance given this XML 

```xml
<abc>
  <def/>
```

Before `def `was highlighted which is wrong. Today it highlights `abc`. When I fixed that I need to fix code action to close abc. There were a lot of bugs and I fixed (by adding new tests) and I support the eat of characters (ex : it fixes the issue https://github.com/eclipse/lemminx/issues/878)

To test correctly this PR, I suggest you do step by step. Ex : 

write 

```xml
<a
```

see if the error range is correct and code action too.

write 

```xml
<a>
```

write 

```xml
<a><b
```

write 

```xml
<a><b>
```

etc...

**Comment by datho7561** [comment]
```xml
<foo>
  <bar><bar></</bar>
</foo>
```
Apply quickfix -->
```xml
<foo>
  <bar><bar</bar></bar>
</foo>
```
Apply quickfix -->
```xml
<foo>
  <bar><bar</bar>></bar>
</foo>
```
This behaviour is slightly different from what happens on master (on master the quickfixes don't help either), but this should probably be fixed in a different PR.

**Comment by datho7561** [comment]
```xml
<foo>
  <bar><bar></bar>
  </bar></</bar>
</foo>
```
Apply quickfix -->
```xml
<foo</foo></foo>
```

**Comment by angelozerr** [comment]
Abandoned for https://github.com/eclipse/lemminx/pull/897

**Pull request closed without merging**
