### PR TITLE
Xml model

### PR DESCRIPTION
**Pull request by BalduinLandolt**
See Issue #633.

Do not review just yet, I'm just trying out things, here...

### CODE REVIEW

**Comment by fbricon** [comment]
[ERROR] /home/jenkins/agent/workspace/lemminx_PR-685/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/dom/DOMDocument.java:[432,61] constructor NoNamespaceSchemaLocation in class org.eclipse.lemminx.dom.NoNamespaceSchemaLocation cannot be applied to given types;
  required: org.eclipse.lemminx.dom.DOMAttr
  found: java.lang.String,<nulltype>
  reason: actual and formal argument lists differ in length

**Comment by BalduinLandolt** [comment]
I am aware this doesn't work as it is. I just drafted the PR so @angelozerr could look into it.

**Comment by angelozerr** [comment]
> I am aware this doesn't work as it is. I just drafted the PR so @angelozerr could look into it.

Yes thanks @BalduinLandolt ! Let me time to create my branch with xml-model and validation

**Comment by angelozerr** [comment]
I close this PR because https://github.com/eclipse/lemminx/pull/709 covers it.

Thanks @BalduinLandolt for your contribution try.

**Pull request closed without merging**
