### PR TITLE
Support references in included files for codelens + diagnostics.

### PR DESCRIPTION
**Pull request by angelozerr**
Search references inincluded files for codelens + diagnostics.

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
Given this XML file:

```xml
<docbook>
	<xref linkend="s1" />
	<section id="s1" />
	<xref linkend="ch1" />
	<xi:include href="sub-book.xml" />
</docbook>
```

with `sub-book.xml` file:

```xml
<book>
	<chapter id="ch1" />
	<chapter id="ch2"/>
	<xref linkend="s1" />
	<xref linkend="s1" />
	<xref linkend="ch1" />
	<xref linkend="ch1" />
</book>
```

and an expression like this:

```json
{
  "pattern": "**/*.xml",
  "expressions": [
    {
      "from": "xref/@linkend",
      "to": "@id"
    }
  ]
}
```

 * the included xref  in sub-book.xml is not used to count codelens: `<section id="s1" />` should show [3 references]
 * the diagnostic report 	`ch1` as an error although it is defined in the sub-book.xml

**Comment by angelozerr** [comment]
> I think that it would be nice to disable this when "xml.validation.xInclude.enabled": false,

I would like to avoid doing that, because my idea is to remove all XSD, RNG support and delegate references with XML references. For XSD, xsd:include is not linked to xiinclude.

For the moment the include is hard coded, but my idea is to give the capability to customize it when you write an xm reference expression like:

{
  "pattern": "**/*.xml",
  "include": [
      "include/@href",
      "import/@href"
   ],
  "expressions": [
    {
      "from": "xref/@linkend",
      "to": "@id"
    }
  ]
}

**Comment by angelozerr** [comment]
> I get a FileNotFoundException when the referenced xi:include/@href doesn't exist

I removed the log

**Review by datho7561 — APPROVED** [review]
Looks good. Thanks, Angelo!

**Pull request merged**
