### PR TITLE
Add xml-model snippets.

### LINKED ISSUE #699: [xml-model] Snippet to generate xml-model
Snippet to generate xml-model and their attributes (with choice). See https://www.w3.org/XML/2010/01/xml-model/

To do that:

 * rename `prolog-snippets.json` to `processing-instruction-snippets.json`
 * write xml-model snippets in `processing-instruction-snippets.json`.

### PR DESCRIPTION
**Pull request by BalduinLandolt**
This PR adds all the changes form #730, but this time it should work.  
All requests for changes are included too.

Fixes #699.

Signed-off-by: Balduin Landolt <balduin.landolt@hotmail.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
It seems perfect
Could you Add fixes  in your commit with the issue number. See other commits to fine samples

**Comment by BalduinLandolt** [comment]
> 
> 
> It seems perfect
> Could you Add fixes in your commit with the issue number. See other commits to find samples

I added "fixes" to the PR description.  
But can I change the commit message after I pushed? Or how can I do that?  
(In any case, for future reference I'll add that right away, of course.)

**Comment by fbricon** [comment]
`git commit --amend` is your friend. See https://help.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message

If you pushed your branch already, then you'll need to force push (`git push -f yourfork yourbranch`), since you're rewriting history. 

That's what you'll need to do since you need to fix the conflict in this PR

**Comment by BalduinLandolt** [comment]
Allrighty... all conflicts resolved, all checks pass. Unless there are any further changes necessary, I'd say it can be merged. :)  
(thanks @angelozerr and @fbricon for your patience!)

**Comment by BalduinLandolt** [comment]
Never mind... I'll fix it and then try again. Sorry!

**Comment by BalduinLandolt** [comment]
Now I'm officially confused: No idea why `CacheResourcesManagerTest.testAvailableCache:99` would fail on me.

**Comment by angelozerr** [comment]
> Now I'm officially confused: No idea why CacheResourcesManagerTest.testAvailableCache:99 would fail on me.

It's not your fault, I created an issue for that https://github.com/eclipse/lemminx/issues/753

> (thanks @angelozerr and @fbricon for your patience!)

@BalduinLandolt congrats for your first contribution! Contributing to a new project can be boring (need to sign some things, need to add some header, need to write commit with a given format, etc...), but now you have done that I think your future (I hope) contribution will be more easy to do. Anyway thank a lot for your PR!

**Pull request merged**
