### PR TITLE
Snippets for xml-stylesheet processing instruction.

### LINKED ISSUE #728: xml-stylesheet snippet
Manage snippet for generating xml-stylesheet processing instruction.

To do that:

 * rename `prolog-snippets.json` to `processing-instruction-snippets.json`
 * write xml-stylesheet snippets in `processing-instruction-snippets.json`.

### PR DESCRIPTION
**Pull request by BalduinLandolt**
Add snippets for xml-stylesheet processing instruction (`<?xml-stylesheet ...?>`).

Fixes #728

Signed-off-by: Balduin Landolt <balduin.landolt@hotmail.com>

### CODE REVIEW

**Comment by BalduinLandolt** [comment]
It works, I guess. Two questions, however:
1. in the tests (`XMLCompletionSnippetsTest.java`), do I need to add all the `c("Instert ..." [etc])` to each `testCompletionFor()`?
1. should I adress the order of the snippets (with `"sortText": ...`)?  
Alphabetic order seems suboptimal here:  
grafik  
I'd rather group xml-model and xml-stylesheet.

**Comment by angelozerr** [comment]
> I'd rather group xml-model and xml-stylesheet.

Indeed, to do that you can use sortText declared in snippet (see https://microsoft.github.io/language-server-protocol/specification#textDocument_completion).

**Comment by BalduinLandolt** [comment]
> Indeed, to do that you can use sortText declared in snippet (see https://microsoft.github.io/language-server-protocol/specification#textDocument_completion).

Done. Looks better now:  
grafik

**Comment by angelozerr** [comment]
> Done. Looks better now:

Definitely, thanks!

Just one question I wonder if we could have several xml-stylesheet processing with the same type in XML document? if you think you can manage that it's fine, otherwise I'm OK to merge it.

**Comment by BalduinLandolt** [comment]
> Just one question I wonder if we could have several xml-stylesheet processing with the same type in XML document? if you think you can manage that it's fine, otherwise I'm OK to merge it.

How do you mean exactly?  
Are you asking if it is supposed to be possible to have multiple? Or are you asking if we should have a snippet to add multiple at once?

As far as I'm aware, nothing speaks against having multiple stylesheets (see the examples here: https://www.w3.org/TR/2010/REC-xml-stylesheet-20101028/ ).

Of course I could have added attribtes like title and alternate, but I don't think they are commonly used, so I left them out. If you think they should be added, that's done quickly.

**Comment by angelozerr** [comment]
> Are you asking if it is supposed to be possible to have multiple?

Yes I mean that.

> As far as I'm aware, nothing speaks against having multiple stylesheets (see the examples here: https://www.w3.org/TR/2010/REC-xml-stylesheet-20101028/ ).

yes in this case perhaps we should improve the filter to check we have one xml-stylesheet?

> Of course I could have added attribtes like title and alternate, but I don't think they are commonly used, so I left them out. If you think they should be added, that's done quickly.

Indeed I agree with you, too many snippets will kill the snippets powerful

**Comment by BalduinLandolt** [comment]
> yes in this case perhaps we should improve the filter to check we have one xml-stylesheet?

Well, as it is now, it allows for multiple stylesheets, which is what we want, I think.
 
> Indeed I agree with you, too many snippets will kill the snippets powerful

Ok. In that case I think it's good to merge.

**Comment by angelozerr** [comment]
Thanks @BalduinLandolt !

**Pull request merged**
