### PR TITLE
Autocompletion of attribute values won't display documentation

### PR DESCRIPTION
**Pull request by angelozerr**
Autocompletion of attribute values won't display documentation

Fixes https://github.com/redhat-developer/vscode-xml/issues/736

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
PR can be reviewed, here a demo:

EnumBug

**Review by AlexXuChen — APPROVED** [review]
LGTM, feature working as intended. Just make sure all CI checks pass before merging.

**Review by JessicaJHee — APPROVED** [review]
The change works perfect for me and the code looks good. But I'm unsure why the build is failing for the checks.

**Comment by angelozerr** [comment]
Thanks so much @AlexXuChen and @JessicaJHee for your review.

**Pull request merged**
