### PR TITLE
Add document link for xi:include

### LINKED ISSUE #1401: DocumentLink support for xi:include/@href
DocumentLink support for xi:include/@href

### PR DESCRIPTION
**Pull request by JessicaJHee**
Peek 2022-12-19 13-21

Fixes #1401

Signed-off-by: Jessica He <jhe@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
It is perfect @JessicaJHee , thanks!

**Comment by angelozerr** [comment]
@oscarlevin I think this feature will interest you. Should be available too in prerelease.

**Comment by oscarlevin** [comment]
This is fantastic!

**Comment by angelozerr** [comment]
@JessicaJHee could you add this feature in vscode xml doc please

**Pull request merged**
