### PR TITLE
Resolve uri as system with XML catalog

### LINKED ISSUE #1199: Resolve uri as system with XML catalog
Given this XMl file:

```xml
<web-app xmlns="http://java.sun.com/xml/ns/j2ee"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee
http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd"
   version="2.4">
```

and this XML catalog:

```xml
<uri name="http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd" uri="file:///...web-app_2_4.xsd"/>
```

The resolved from XML catalog (which should return `file:///...web-app_2_4.xsd)` is not done for `http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd` (which is teh system).

Today resolve with uri is done for namespace, ex: 

```xml
<uri name="http://java.sun.com/xml/ns/j2ee" uri="file:///...web-app_2_4.xsd"/>
```

should work.

### PR DESCRIPTION
**Pull request by angelozerr**
Resolve uri as system with XML catalog

Fixes #1199

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
Test are now written, the PR is ready.

**Comment by rgrunber** [comment]
Is this correct for the WWD system-catalog.xml ?

```
$ cat /tmp/foo/foospace/.metadata/.plugins/org.eclipse.wildwebdeveloper.xml/system-catalog.xml
<?xml version="1.0"?>
<!DOCTYPE catalog PUBLIC "-//OASIS//DTD Entity Resolution XML Catalog V1.0//EN" "http://www.oasis-open.org/committees/entity/release/1.0/catalog.dtd">
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog" prefer="public">
```

If I set this file as an item of `xml.catalog` and ensure `~/.lemminx/` is empty before opening the above sample xml files, I still get the following files created in the lemminx cache :

```
$HOME/.lemminx/cache/http/java.sun.com/xml/ns/j2ee/web-app_2_4.xsd
$HOME/.lemminx/cache/http/www.w3.org/2001/xml.xsd
$HOME/.lemminx/cache/http/xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd
```

**Comment by angelozerr** [comment]
> Is this correct for the WWD system-catalog.xml ?

It seems it is empty, so it is not correct. Have you WTP which is installed? Which version of WWD do you have?

> If I set this file as an item of xml.catalog and ensure ~/.lemminx/ is empty before opening the above sample xml files, I still get the following files created in the lemminx cache

Since your system-cataog.xml is empty, it is the correct behavior.

**Review by rgrunber — APPROVED** [review]
I was just missing the WTP dependencies. When I installed them separately I was able to open the files with nothing being generated in the cache.

**Comment by angelozerr** [comment]
Thanks @rgrunber for your review.

**Pull request merged**
