### PR TITLE
Fix completion & hover based on XSD with elementFormDefault="unqualified"

### PR DESCRIPTION
**Pull request by angelozerr**
Fix completion & hover based on XSD with elementFormDefault="unqualified"

See https://github.com/redhat-developer/vscode-xml/issues/311

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
To test this PR:

 * open `foo-qualified.xml`  which is in this PR
 * open completion after bar, you should see item (the fix).

or try  the user usecase https://github.com/redhat-developer/vscode-xml/issues/311#issue-682116842

**Comment by datho7561** [comment]
For the user use case, I tried deleting `<subtitle></subtitle>` element, and then opening completion. It is specified as min 0 max 1, but it isn't suggested. If I open completion after `<subtitle></subtitle>`, it suggests adding another subtitle element:
SubtitleDoesntAppearUntilAfter

**Comment by angelozerr** [comment]
@datho7561 have you configured the XML catalog?

**Comment by datho7561** [comment]
> @datho7561 have you configured the XML catalog?

Thanks oops.

**Comment by datho7561** [comment]
I configured the catalog, and now it works for the root level, but not nested elements:

NestedStillDoesntWork

**Comment by angelozerr** [comment]
> I configured the catalog, and now it works for the root level, but not nested elements:

Indeed there were a problem with XML catalog. Please retry it.

**Pull request merged**
