### PR TITLE
DTD validation doesn't work with XML catalog and PUBLIC declaration

### LINKED ISSUE #847: DTD validation doesn't work with XML catalog and PUBLIC declaration
* Download  https://github.com/dita-ot/dita-ot/releases/download/3.5.1/dita-ot-3.5.1.zip
 * set settings `"xml.validation.resolveExternalEntities": true,`
 * Register as catalog `dita-ot-3.5.1\\catalog-dita.xml`
 * Open `dita-ot-3.5.1\docsrc\site.ditamap`

You have a lot of errors (because the DTD cannot be resolved):

image

Although you should have no errors like

image

### PR DESCRIPTION
**Pull request by angelozerr**
DTD validation doesn't work with XML catalog and PUBLIC declaration

Fixes #847

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
This PR should fix #847 but I must write tests

**Comment by angelozerr** [comment]
To test this PR:

 * Download  https://github.com/dita-ot/dita-ot/releases/download/3.5.1/dita-ot-3.5.1.zip
 * set settings `"xml.validation.resolveExternalEntities": true,`
 * Register as catalog `dita-ot-3.5.1\\catalog-dita.xml`
 * Open `dita-ot-3.5.1\docsrc\site.ditamap`

You should have none errors:

image

If you try to add some bad XML element (ex : `<a />`) you should see the error.

**Comment by datho7561** [comment]
I get this error when I open `site.ditamap`:

```
Message: Unexpected XMLValidator error
java.lang.StringIndexOutOfBoundsException: String index out of range: 7454
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at org.eclipse.lemminx.utils.XMLPositionUtility.getEntityReferenceStartOffset(XMLPositionUtility.java:618)
	at org.eclipse.lemminx.utils.XMLPositionUtility.selectEntityReference(XMLPositionUtility.java:585)
	at org.eclipse.lemminx.utils.XMLPositionUtility.selectEntityReference(XMLPositionUtility.java:567)
	at org.eclipse.lemminx.extensions.contentmodel.participants.DTDErrorCode.toLSPRange(DTDErrorCode.java:169)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.LSPErrorReporterForXML.toLSPRange(LSPErrorReporterForXML.java:68)
	at org.eclipse.lemminx.extensions.xerces.AbstractLSPErrorReporter.internalToLSPRange(AbstractLSPErrorReporter.java:147)
	at org.eclipse.lemminx.extensions.xerces.AbstractLSPErrorReporter.reportError(AbstractLSPErrorReporter.java:84)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLDTDScannerImpl.startPE(Unknown Source)
	at org.apache.xerces.impl.XMLDTDScannerImpl.scanEntityValue(Unknown Source)
	at org.apache.xerces.impl.XMLDTDScannerImpl.scanEntityDecl(Unknown Source)
	at org.apache.xerces.impl.XMLDTDScannerImpl.scanDecls(Unknown Source)
	at org.apache.xerces.impl.XMLDTDScannerImpl.scanDTDExternalSubset(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentScannerImpl$DTDDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.XMLValidator.parseXML(XMLValidator.java:108)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.XMLValidator.doDiagnostics(XMLValidator.java:94)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.ContentModelDiagnosticsParticipant.doDiagnostics(ContentModelDiagnosticsParticipant.java:48)
	at org.eclipse.lemminx.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:85)
	at org.eclipse.lemminx.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:53)
	at org.eclipse.lemminx.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:159)
	at org.eclipse.lemminx.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:168)
	at org.eclipse.lemminx.XMLTextDocumentService.validate(XMLTextDocumentService.java:466)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$triggerValidationFor$23(XMLTextDocumentService.java:459)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by angelozerr** [comment]
have you set settings "xml.validation.resolveExternalEntities": true?

**Comment by datho7561** [comment]
> have you set settings "xml.validation.resolveExternalEntities": true?

Oops. No, sorry. I will try again.

**Comment by angelozerr** [comment]
> I think that the error case where the validator crashes when external entities are not resolved should be handled more gracefully, but that might make sense to have in another PR.

Indeed I had noticed the problem, see https://github.com/eclipse/lemminx/issues/853

**Comment by angelozerr** [comment]
Thanks @datho7561 for your review!

**Pull request merged**
