### PR TITLE
Check for null elementOptionality entry for code action cvc_complex_type_2_4_b

### LINKED ISSUE #1280: Null pointer exception when processing code action cvc_complex_type_2_4_b
Based on this comment: https://github.com/eclipse/lemminx/pull/1257#discussion_r947977144

When the element does not have an optionality entry in the elementOptionality list, a NPE is triggered.

### PR DESCRIPTION
**Pull request by JessicaJHee**
Fixes #1280 

Signed-off-by: Jessica He [jhe@redhat.com](mailto:jhe@redhat.com)

### CODE REVIEW

**Comment by angelozerr** [comment]
@JessicaJHee do you think we could have a simple test for this PR? If it is too complex, please ignore my comment.

**Comment by JessicaJHee** [comment]
> @JessicaJHee do you think we could have a simple test for this PR? If it is too complex, please ignore my comment.

yes we can, but the result from the code action would be incorrect.

**Comment by angelozerr** [comment]
Yes you are righr but this test will be fixed again with 
https://github.com/eclipse/lemminx/issues/1278

I mean that you will have test that you should adjust.

**Comment by angelozerr** [comment]
Thanks @JessicaJHee !

**Pull request merged**
