### PR TITLE
Support joinCDATALines setting with experimental formatter

### LINKED ISSUE #1241: Support `xml.format.joinCDATALines` setting with experimental formatter
See https://github.com/redhat-developer/vscode-xml/blob/master/docs/Formatting.md#xmlformatjoincdatalines

### PR DESCRIPTION
**Pull request by JessicaJHee**
Peek 2022-09-09 11-58

Fixes #1241 

Signed-off-by: Jessica He <jhe@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
The code looks good. @donat il there any chance Thatcher yiu review it by trying it please 

@JessicaJHee we have several issues with cdata formatting in vscode XML Android lemminx. I Wonder if your PR fixes some issues.

**Comment by JessicaJHee** [comment]
> @JessicaJHee we have several issues with cdata formatting in vscode XML Android lemminx. I Wonder if your PR fixes some issues.

Yes I believe it does. For this issue https://github.com/redhat-developer/vscode-xml/issues/719, this setting should work with the experimental formatter as tested.

For this issue https://github.com/eclipse/lemminx/issues/1193, it satisfies the suggestions since there is currently no formatting for the CDATA section with the experimental formatter. There is only formatting when the joinCDATALines setting is set to true.

**Comment by angelozerr** [comment]
OK great I should be really nice if you could write a test per issues by adding a link  to the issue. Once the PR will be merged please close the issues by adding it i should be fixed with experimental formatter. Thanks

**Comment by datho7561** [comment]
One bug I noticed while playing with the code was:

```xml
<aaa Name=""><![CDATA[asdf asdf asdf]]></aaa>
```

If you format with join CDATA lines on, you get:

```xml
<aaa Name=""><![CDATA[asdf asdfasdf]]></aaa>
```

**Pull request merged**
