### PR TITLE
Autoclose tag generates an unexpected >

### LINKED ISSUE #1221: Autoclose tag generates an unexpected >
Given this XML file:

`<foo</foo>`

when we close the foo start tag:

`<foo>`

the auto class tag (I think) generates a `>`

`<foo</foo>>`

### PR DESCRIPTION
**Pull request by angelozerr**
Autoclose tag generates an unexpected >

Fixes #1221

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
@vrubezhny @mickaelistria this PR removes the wordPattern which fixes https://github.com/eclipse/lemminx/issues/1221 issue.

I have tried quickly with WWD and without this PR, there is the same problem than vscode.

It seems that you improve LSP4e linked editing, so I would like to apply this PR:

 * to be consistent with HTML LS (linked editing doesn't return wordPattern)
 * to have a JSON response which is smaller
 * to avoid the issue https://github.com/eclipse/lemminx/issues/1221

**Review by datho7561 — APPROVED** [review]
This works for me. Thank you, Angelo!

**Comment by angelozerr** [comment]
Thanks @datho7561 for your review.

@vrubezhny @mickaelistria can we merge the PR?

**Comment by angelozerr** [comment]
@mickaelistria @vrubezhny I suggest we merge the PR since HTML LS works without Word pattern. 

If there are some problem in eclipse ide we will use again Word pattern but by taking care of the fixed issue.

**Pull request merged**
