### PR TITLE
Improve readability of the first line in error messages.

### LINKED ISSUE #1145: XML validation errors of "Language Servers" are only partially visible
This is from Eclipse 2021-12 (4.22): this xml snippet causes two validation errors:

```
<application xmlns="https://jakarta.ee/xml/ns/jakartaee"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/application_9.xsd">
	<invalid>
	</invalid>
</application>
```

The "Language Servers" section shows only the headers of the error message, in my sample "Attribute:" and "Invalid element name".
Markers View
The other two errors seem to result from the WTP XML validator.

Copying the details shows the full error:
```
Attribute:
 - version
is required in element:
 - application
```
And:
```
Invalid element name:
 - invalid

One of the following is expected:
 - application-name
 - description
 - display-name
 - icon
 - initialize-in-order
 - module
```

So, the "Markers" views should either remove the newlines or display multiline texts.

Hope this is the right place to report this issue.

### PR DESCRIPTION
**Pull request by JessicaJHee**
image
image

Fixes #1145 

Signed-off-by: Jessica He <jhe@redhat.com>

### CODE REVIEW

**Review by datho7561 — CHANGES_REQUESTED** [review]
There are a few other error messages that I think could be changed that are in the `XMLSchemaMessagesReformatted.properties` file:
- cvc-complex-type.2.4.a
- cvc-complex-type.4

**Comment by JessicaJHee** [comment]
> There are a few other error messages that I think could be changed that are in the `XMLSchemaMessagesReformatted.properties` file:
> 
> * cvc-complex-type.2.4.a
> * cvc-complex-type.4

I believe these are already updated?
https://github.com/eclipse/lemminx/blob/0d2041b4079c9b80c1a0544b01fa91204c1d5882/org.eclipse.lemminx/src/main/resources/XMLSchemaMessagesReformatted.properties#L28

https://github.com/eclipse/lemminx/blob/0d2041b4079c9b80c1a0544b01fa91204c1d5882/org.eclipse.lemminx/src/main/resources/XMLSchemaMessagesReformatted.properties#L32

**Comment by datho7561** [comment]
> I believe these are already updated?

Yes, they were. My bad.

**Review by datho7561 — APPROVED** [review]
Looks good. Thanks Jessica!

**Pull request merged**
