### PR TITLE
Allow extensions to contribute WorkspaceService

### PR DESCRIPTION
**Pull request by mickaelistria**
For executeCommand, didChangeConfiguration, didChangeWatchedFiles,
didChangeWorkspaceFolders

Signed-off-by: Mickael Istria <mistria@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
It looks promising. Is there any chance to have some tests with your feature please?

**Comment by mickaelistria** [comment]
I'll try to add tests. I wanted to share this ASAP to get some early feedback on the API and the overall approach.

**Comment by mickaelistria** [comment]
I added some tests.

**Comment by mickaelistria** [comment]
See https://github.com/eclipse/lemminx-maven/pull/189 as an example of how client can adopt this. Getting rid of the need to use doSave by the way is a major win!

**Pull request closed without merging**
