### PR TITLE
xsd:enumeration autocomplete don't work for text node

### PR DESCRIPTION
**Pull request by angelozerr**
xsd:enumeration autocomplete don't work for text node

Fixes https://github.com/redhat-developer/vscode-xml/issues/218

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
To test this PR, see usecase at https://github.com/redhat-developer/vscode-xml/issues/218#issue-547209289

 * when you apply completion to insert `ACTION-TYPE`, it should show choice of xsd:enumeration
 * when you have `<ACTION-TYPE>|<ACTION-TYPE>` it should show list of xsd:enumeration.

Here a demo which shows in action xs:enumeration on text:

XSDEnumerationOnText

**Comment by fbricon** [comment]
Looks promising. Could you plug the "did you mean" feature in? I don't remember if we implemented it in lemminx

**Comment by angelozerr** [comment]
This PR is ready (there are some tests), the only part which is not managed is the documentation for the xs:enumeration value (see the FIXME).

I don't know how to manage that for the moment. I think we should create an another issue to manage that and support hover together.

**Comment by angelozerr** [comment]
> Looks promising. Could you plug the "did you mean" feature in? I don't remember if we implemented it in lemminx

What do ypou mean with  `Could you plug the "did you mean" feature in?`

> I don't remember if we implemented it in lemminx

No it was not implemented and my PR implements that.

**Comment by xorye** [comment]
I came across some bugs:
On my machine, there are three failing tests:
```
[ERROR] Failures: 
[ERROR]   DTDCompletionExtensionsTest.testNoDuplicateCompletionItems:186->testCompletionFor:202 expected: <5> but was: <2>
[ERROR]   DTDCompletionWithCacheExtensionsTest.dtdCache:70 desc should only exist once: Actual: End with '</animate>',End with '</svg>',#region,#endregion,cdata,comment ==> expected: <1> but was: <0>
[ERROR]   XMLSchemaCompletionExtensionsTest.noNamespaceSchemaLocationCompletion:223 expected: <<OutOfBand></OutOfBand>> but was: <<OutOfBand>false</OutOfBand>>
```

Also, the completion and validation does not seem to work after I open AUTOSAR_00048.xsd:
demo

**Comment by angelozerr** [comment]
> Also, the completion and validation does not seem to work after I open AUTOSAR_00048.xsd

Yes please don't open it:) The problem with this XML Schema is that it generates too many symbols (you can exclude the symbols for this files in the settings), but I'm glad that you have seen the problem and now I think you will understand why https://github.com/redhat-developer/vscode-xml/issues/237 is very important :)

**Comment by angelozerr** [comment]
> On my machine, there are three failing tests:

That's strange, travis doesnt fail?

**Comment by angelozerr** [comment]
@xorye please retry

**Comment by xorye** [comment]
It works!

**Comment by xorye** [comment]
> Yes please don't open it:) The problem with this XML Schema is that it generates too many symbols (you can exclude the symbols for this files in the settings), but I'm glad that you have seen the problem and now I think you will understand why redhat-developer/vscode-xml#237 is very important :)

I see. I still get this problem when I disable symbols/exclude the file. I can investigate more while taking care of redhat-developer/vscode-xml#237

**Pull request merged**
