### PR TITLE
Prevent the unit tests from using `~/.lemminx` or `~/cache`

### LINKED ISSUE #1265: Unit tests should not store data in ~/.lemminx
Unit tests currently write data in ~/.lemminx, this is wrong:

>[INFO] Running XML Validation Command Test
2022-07-29 10:22:14.995:INFO::main: Logging initialized @19707ms to org.eclipse.jetty.util.log.StdErrLog
2022-07-29 10:22:15.094:INFO:oejs.Server:main: jetty-9.4.41.v20210516; built: 2021-05-16T23:56:28.993Z; git: 98607f93c7833e7dc59489b13f3cb0a114fb9f4c; jvm 17.0.1+12
2022-07-29 10:22:15.146:INFO:oejs.AbstractConnector:main: Started ServerConnector@7c40ffef{HTTP/1.1, (http/1.1)}{0.0.0.0:55113}
2022-07-29 10:22:15.146:INFO:oejs.Server:main: Started @19858ms
Jul 29, 2022 10:22:15 AM org.eclipse.lemminx.uriresolver.FileServer start
INFO: http server started on port 55113
Jul 29, 2022 10:22:15 AM org.eclipse.lemminx.uriresolver.FileServer getUri
INFO: remote uri : http://localhost:55113/tag.xsd
Jul 29, 2022 10:22:15 AM org.eclipse.lemminx.uriresolver.FileServer getUri
INFO: remote uri : http://localhost:55113/tag.dtd
Jul 29, 2022 10:22:15 AM org.eclipse.lemminx.uriresolver.CacheResourcesManager lambda$downloadResource$0
INFO: Downloading http://localhost:55113/tag.xsd to /Users/fbricon/.lemminx/cache/http/localhost/55113/tag.xsd...
Jul 29, 2022 10:22:15 AM org.eclipse.lemminx.uriresolver.CacheResourcesManager lambda$downloadResource$0
INFO: Downloaded http://localhost:55113/tag.xsd to /Users/fbricon/.lemminx/cache/http/localhost/55113/tag.xsd in 111ms
Jul 29, 2022 10:22:17 AM org.eclipse.lemminx.uriresolver.CacheResourcesManager lambda$downloadResource$0
INFO: Downloading http://localhost:55113/tag.dtd to /Users/fbricon/.lemminx/cache/http/localhost/55113/tag.dtd...
Jul 29, 2022 10:22:17 AM org.eclipse.lemminx.uriresolver.CacheResourcesManager lambda$downloadResource$0
INFO: Downloaded http://localhost:55113/tag.dtd to /Users/fbricon/.lemminx/cache/http/localhost/55113/tag.dtd in 4ms
Jul 29, 2022 10:22:21 AM org.eclipse.lemminx.uriresolver.CacheResourcesManager lambda$downloadResource$0
INFO: Downloading http://localhost:55113/tag.dtd to /Users/fbricon/.lemminx/cache/http/localhost/55113/tag.dtd...
Jul 29, 2022 10:22:21 AM org.eclipse.lemminx.uriresolver.CacheResourcesManager lambda$downloadResource$0
INFO: Downloading http://localhost:55113/tag.xsd to /Users/fbricon/.lemminx/cache/http/localhost/55113/tag.xsd...
Jul 29, 2022 10:22:21 AM org.eclipse.lemminx.uriresolver.CacheResourcesManager lambda$downloadResource$0
INFO: Downloaded http://localhost:55113/tag.dtd to /Users/fbricon/.lemminx/cache/http/localhost/55113/tag.dtd in 3ms
Jul 29, 2022 10:22:21 AM org.eclipse.lemminx.uriresolver.CacheResourcesManager lambda$downloadResource$0
INFO: Downloaded http://localhost:55113/tag.xsd to /Users/fbricon/.lemminx/cache/http/localhost/55113/tag.xsd in 3ms
2022-07-29 10:22:22.373:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@7c40ffef{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
2022-07-29 10:22:22.375:INFO:oejs.Server:main: jetty-9.4.41.v20210516; built: 2021-05-16T23:56:28.993Z; git: 98607f93c7833e7dc59489b13f3cb0a114fb9f4c; jvm 17.0.1+12
2022-07-29 10:22:22.377:INFO:oejs.AbstractConnector:main: Started ServerConnector@5d05f453{HTTP/1.1, (http/1.1)}{0.0.0.0:55126}
2022-07-29 10:22:22.377:INFO:oejs.Server:main: Started @27089ms
Jul 29, 2022 10:22:22 AM org.eclipse.lemminx.uriresolver.FileServer start

Screenshot 2022-07-29 at 10 24 56

Tests should use a clean cache directory, that would not pollute the user cache and also ensure idempotency

### PR DESCRIPTION
**Pull request by datho7561**
Closes #1265

### CODE REVIEW

**Comment by datho7561** [comment]
I timed the tests before and after this change on my laptop; I got:

with change:
1m16.430s
1m15.037s
1m14.861s
1m15.306s
1m14.323s

without change:
1m15.780s
1m14.240s
1m14.666s
1m14.573s
1m14.430s

I used an online t test calculator, and it told me that the difference was not statistically significant (p-value 0.3341)

**Comment by angelozerr** [comment]
That's great, thanks @datho7561 for your feedback.

**Comment by rgrunber** [comment]
This change definitely stops all logging to `~/.lemminx` & `~/cache` . Would it be possible to create a folder `lemminx` under the temp directory, and create the cached folders there ? Just for the sake of not creating a bunch of directories under the tmp root.

I also noticed temporary files of the form `*.lemminx` (eg. `spring-beans*.lemminx`) being created in the temp directory root. Could we also place those within that lemminx folder ?

**Comment by datho7561** [comment]
> This change definitely stops all logging to `~/.lemminx` & `~/cache` . Would it be possible to create a folder `lemminx` under the temp directory, and create the cached folders there ? Just for the sake of not creating a bunch of directories under the tmp root.

Of course!

> I also noticed temporary files of the form `*.lemminx` (eg. `spring-beans*.lemminx`) being created in the temp directory root. Could we also place those within that lemminx folder ?

I've been looking into what's generating these files; it's taking a bit longer than I was expecting, but I'll figure it out.

**Comment by datho7561** [comment]
> I've been looking into what's generating these files; it's taking a bit longer than I was expecting, but I'll figure it out.

It's the cache manager :D https://github.com/eclipse/lemminx/blob/b0959037b9fb23efb4816077f8b841c35d8e3386/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/uriresolver/CacheResourcesManager.java#L225. Seems like we download to a temporary folder before moving stuff to a more permanent place on the filesystem. I'll make sure that these get direct into a subdirectory of `/tmp` so we aren't polluting it.

**Review by rgrunber — APPROVED** [review]
This change works fine for me. The cached files seem to be entirely within tmpdir. Feel free to merge when ready.

**Pull request merged**
