### PR TITLE
Display test names in a more user-friendly way

### PR DESCRIPTION
**Pull request by fbricon**

### CODE REVIEW

**Comment by fbricon** [comment]
See new display names in Jenkins: https://ci.eclipse.org/lemminx/job/lemminx/view/change-requests/job/PR-647/lastCompletedBuild/testReport/(root)/

**Comment by fbricon** [comment]
@angelozerr @xorye worth it or not?

**Comment by fbricon** [comment]
There, Class names unchanged, method names beautified:

https://ci.eclipse.org/lemminx/job/lemminx/view/change-requests/job/PR-647/lastCompletedBuild/testReport/org.eclipse.lemminx.uriresolver/CacheResourcesManagerTest/

Screen Shot 2020-04-22 at 6 50 36 PM

CLI build output:
Screen Shot 2020-04-22 at 6 49 44 PM

In Eclipse JUnit view, Class names and method names are beautified, but clicking on them links to proper locations:
Screen Shot 2020-04-22 at 6 53 22 PM

Nothing changes in vscode test view, seems they don't support `@DisplayName`

**Comment by xorye** [comment]
I'm good with this being merged

**Pull request merged**
