### PR TITLE
Completion for external declared entity

### LINKED ISSUE #660: Completion for external declared entity
The issue https://github.com/eclipse/lemminx/issues/520 manages internal entity. When XML file is bound to a DTD which defines entities, completion for external entities should be available.

### PR DESCRIPTION
**Pull request by angelozerr**
Completion for external declared entity

Fixes #660

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
Please don't review the code, I need to clean some code and write test but you can play with this PR.

To do that, create a DTD file `base.dtd` which defines the `external` entity:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<!ELEMENT root-element (#PCDATA)>
<!ENTITY external "EXTERNALLY DECLARED ENTITY">
```

create a XML file like this:

```xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE root-element SYSTEM "base.dtd" [
	<!ENTITY local "LOCALLY DECLARED ENTITY">
]>   
<root-element>
   |
</root-element>
```

You should see external entity coming from the base.dtd:

image

@xorye if you have time, could you play with this PR and  give me feedback if you find some trouble please. Thanks!

**Comment by angelozerr** [comment]
@xorye @fbricon you can review my PR, code should be clean and test exsists. Thanks!

**Comment by xorye** [comment]
The PR works & looks good to me

**Comment by angelozerr** [comment]
Thanks @xorye !

**Pull request merged**
