### PR TITLE
NPE on xsd datatype autocompletion in binary mode

### LINKED ISSUE #1189: NPE on xsd datatype autocompletion in binary mode
Hi there, 

we're having an issue on several computers running version 0.19.1, both Linux and Windows, while trying to autocomplete an XSD document. Find below the stacktrace.

`[Info  - 17:42:04] Mar 22, 2022 05:42:04 org.eclipse.lemminx.XMLLanguageServer initialize()
Message: Initializing XML Language server
LemMinX Server info:
 - Version : 0.19.1
 - Native Image
 - VM Version : 11.0.9
 - Git [Branch 6059965ad91cd67cba1c91f4b82714c57dc64fa5] 6059965 - [maven-release-plugin] prepare release 0.19.1
[Error - 17:42:10] Mar 22, 2022 05:42:10 org.eclipse.lemminx.services.XMLCompletions collectAttributeValueSuggestions()
Message: While performing ICompletionParticipant#onAttributeValue for participant 'org.eclipse.lemminx.extensions.xsd.participants.XSDCompletionParticipant'.
java.lang.NullPointerException
    at org.eclipse.lemminx.extensions.xsd.DataType.getDataTypes(DataType.java:46)
    at org.eclipse.lemminx.extensions.xsd.participants.XSDCompletionParticipant.onAttributeValue(XSDCompletionParticipant.java:79)
    at org.eclipse.lemminx.services.XMLCompletions.collectAttributeValueSuggestions(XMLCompletions.java:919)
    at org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:153)
    at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:151)
    at org.eclipse.lemminx.XMLTextDocumentService.lambda$completion$1(XMLTextDocumentService.java:223)
    at java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
    at java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
    at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
    at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
    at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)`

Thanks in advance 🙇‍♂️

### PR DESCRIPTION
**Pull request by angelozerr**
NPE on xsd datatype autocompletion in binary mode

Fixes #1189

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
To reproduce the problem, 

 * set the `"xml.server.preferBinary": true` in the settings.json to use binary.
 * create a XSD file `test.xsd`:
 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="foo" type="" />
</xs:schema>
```

and try to open completion on type attribute value

`<xs:element name="foo" type="|`

The completion should provide xs types but it failed and in the stacktrace there is the NPE.

It works with Java but not with binary. This PR should fix the problem.

**Comment by jagui** [comment]
LGTM

Can repro setting `"xml.server.preferBinary": true` 

Great job. Thanks, @angelozerr

**Comment by angelozerr** [comment]
> LGTM

Have you tried with binary?

**Comment by rgrunber** [comment]
I'm able to reproduce the issue from https://github.com/eclipse/lemminx/issues/1189#issue-1181064860 . However, with this PR, I now get a different stacktrace :

```
[Error - 6:11:54 PM] Mar 28, 2022 06:11:54 org.eclipse.lemminx.extensions.xsd.DataType loadDataTypes()
Message: Error while loading data types with file '/schemas/xsd/datatypes.xml'.
java.net.MalformedURLException
	at java.net.URL.<init>(URL.java:708)
	at java.net.URL.<init>(URL.java:569)
	at java.net.URL.<init>(URL.java:516)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.eclipse.lemminx.extensions.xsd.DataType.loadDataTypes(DataType.java:116)
	at org.eclipse.lemminx.extensions.xsd.DataType.<clinit>(DataType.java:43)
	at org.eclipse.lemminx.extensions.xsd.participants.XSDCompletionParticipant.onAttributeValue(XSDCompletionParticipant.java:79)
	at org.eclipse.lemminx.services.XMLCompletions.collectAttributeValueSuggestions(XMLCompletions.java:919)
	at org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:153)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:151)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$completion$1(XMLTextDocumentService.java:223)
	at java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1311)
	at java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1280)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
Caused by: java.lang.NullPointerException
	at java.net.URL.<init>(URL.java:614)
	... 27 more
```

I tried with the binary produced by this build, as well as my own locally build binary. The stacktrace is the same.

**Comment by jagui** [comment]
Same here with the latest commit:

```[Info  - 12:16:14 AM] Mar 29, 2022 12:16:14 org.eclipse.lemminx.XMLLanguageServer initialize()

Message: Initializing XML Language server
LemMinX Server info:
 - Version : 0.19.2-SNAPSHOT
 - Native Image
 - VM Version : 17.0.2
 - Git [Branch cf4011c03a1338329212945ebb3c98c9588be4e6] cf4011c - NPE on xsd datatype autocompletion in binary mode
[Error - 12:16:26 AM] Mar 29, 2022 12:16:26 org.eclipse.lemminx.extensions.xsd.DataType loadDataTypes()
Message: Error while loading data types with file '/schemas/xsd/datatypes.xml'.
java.net.MalformedURLException
	at java.net.URL.<init>(URL.java:708)
	at java.net.URL.<init>(URL.java:569)
	at java.net.URL.<init>(URL.java:516)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.eclipse.lemminx.extensions.xsd.DataType.loadDataTypes(DataType.java:116)
	at org.eclipse.lemminx.extensions.xsd.DataType.<clinit>(DataType.java:43)
	at org.eclipse.lemminx.extensions.xsd.participants.XSDCompletionParticipant.onAttributeValue(XSDCompletionParticipant.java:79)
	at org.eclipse.lemminx.services.XMLCompletions.collectAttributeValueSuggestions(XMLCompletions.java:919)
	at org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:153)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:151)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$completion$1(XMLTextDocumentService.java:223)
	at java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1311)
	at java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1280)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
Caused by: java.lang.NullPointerException
	at java.net.URL.<init>(URL.java:614)
	... 27 more
```

**Comment by jagui** [comment]
```LemMinX Server info:
 - Version : 0.19.2-SNAPSHOT
 - Native Image
 - VM Version : 17.0.2
 - Git [Branch 0b7fdf92363e8be5a41aa7d52594a7757d36cf01] 0b7fdf9 - NPE on xsd datatype autocompletion in binary mode
 ``` 
NPE is gone, autocomplete works.

**Comment by angelozerr** [comment]
My bad, the fix was indeed wrong, I updated and the fix is to declare the data.xml in the `resource-config.json`:

```
{
	"pattern": "\\Qschemas/xsd/datatypes.xml\\E"
}
```

I tested on Windows and it works. I'm pretty sure that it works with other OS, because it works with another usecase like `schemas/xsd/xml.xsd`. I did the same for datatypes.xml.

**Comment by angelozerr** [comment]
> NPE is gone, autocomplete works.

Thanks @jagui for your feedback. We should create the release today.

**Comment by jagui** [comment]
Thanks @angelozerr for the prompt response and kudos on such a great project documentation. It was really easy to get build the binary/java versions and test them with the vscode extension.

**Pull request merged**
