### PR TITLE
Fix bug with selection formatting outside of range

### LINKED ISSUE #1485: Partial formating yields wrong intendation deep
If I format only a part of the document one gets wrong indentation, e.g.:

## Current
image

## Expected
image

### PR DESCRIPTION
**Pull request by JessicaJHee**
Fixes #1485 

Peek 2023-02-17 12-43

### CODE REVIEW

**Review by datho7561 — APPROVED** [review]
Works very well! Thanks, Jessica!

**Comment by datho7561** [comment]
This PR addresses the issue Fred pointed out in his comment https://github.com/eclipse/lemminx/issues/1485#issuecomment-1434591999, but I think the issue 
Christoph pointed out might be related to the limitations of lsp4e with regards to managing spaces vs. tabs (it can't be managed on a per-file type basis from what I understand).

**Comment by laeubi** [comment]
@datho7561 I always wondered if not simply the current file style could be used when doing partial formats? I can't think about a use case where a mixed style is desirable (except the file is already mixed type).

**Comment by angelozerr** [comment]
For formatting it will work, but if you pres tabs (and your configuration is tab), it will generate a tab although you would like to have 2 spaces.

**Comment by laeubi** [comment]
I must confess I never really "configured" this :-)
Just from an users POV, the editor should be smart enough by default to simply translate this, let it be partial (or even full!) format or pressing a key that means "indent it some bit". But if it is only partially supported, even that could help, because at least I mostly use auto format rather than start intended the code/xml myself...

**Comment by angelozerr** [comment]
Before the pom.xml used WTP XML Editor. You can open it with:

image

And I think you should have this settings:

image

Today, the Maven POM Editor uses Generic Editor which uses for XML, lemminx, but badly GenericEditor cannot be configured with custom XML tabs / spaces for a given language.

**Pull request merged**
