### PR TITLE
XSD with targetNamespace cannot be used with xml.fileAssociations

### PR DESCRIPTION
**Pull request by angelozerr**
XSD with targetNamespace cannot be used with xml.fileAssociations

See https://github.com/redhat-developer/vscode-xml/issues/223

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
To test this PR, create the `tei.xml` without `xsi:schemaLocation` like this :

```xml
<?xml version="1.0" encoding="UTF-8"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0" >
  <teiHeader>
    <fileDesc>
      <titleStmt><title>dummy</title></titleStmt>
      <publicationStmt><publisher>dummy</publisher></publicationStmt>
      <sourceDesc><p>dummy</p></sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body><p>dummy</p></body>
  </text>
</TEI>
```

Declare a fileassociation like this:

```json
"xml.fileAssociations": [
      {
         "pattern": "tei.xml",
         "systemId": "http://www.tei-c.org/ns/1.0 https://tei-c.org/Vault/P5/current/xml/tei/custom/schema/xsd/tei_all.xsd"
      }
   ]
```

and you should have validation and completion based on https://tei-c.org/Vault/P5/current/xml/tei/custom/schema/xsd/tei_all.xsd

The main idea is that systemId has the same content than xsi:schemaLocation
xsi:schemaLocation="http://www.tei-c.org/ns/1.0 https://tei-c.org/Vault/P5/current/xml/tei/custom/schema/xsd/tei_all.xsd"

I set my PR as draft since I must work tests.

**Comment by angelozerr** [comment]
I notice that only validation is working, completion based on XSD doesn't work. I must improve the PR again.

**Comment by angelozerr** [comment]
@datho7561 everything should work (completion, hover and diagnostics based on XSD with a namespace). Please re-read my comments https://github.com/eclipse/lemminx/pull/924#issuecomment-721803909 that I have updated.

**Comment by datho7561** [comment]
> To test this PR, create the `tei.xml` without `xsi:schemaLocation` like this :

This demo doesn't work for me. The root `TEI` element is marked as `cvc-elt.1.a`

**Review by datho7561 — APPROVED** [review]

**Comment by yatli** [comment]
Hi!

I'm still trying to work out the MSBuild use scenario.
Their schema is not retrievable at http://schemas.microsoft.com/developer/msbuild/2003, but they do provide xsd targeting the namespace.

As of `v0.14.1` I'm still hitting the error:

```
[xml TargetNamespace.2] [E] TargetNamespace.2: Expecting no namespace, but the schema document has a target namespace of 'http://schemas.microsoft.com/developer/msbuild/2003'.
```

**Comment by angelozerr** [comment]
@yatli could you create a new issue with your use case by adding your XML file, your XML file association, etc. Thanks.

**Comment by yatli** [comment]
Thanks @angelozerr , see https://github.com/eclipse/lemminx/issues/935

**Pull request merged**
