### PR TITLE
Rename not completing with binary

### PR DESCRIPTION
**Pull request by angelozerr**
Rename not completing with binary

Fixes https://github.com/redhat-developer/vscode-xml/issues/424

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by rgrunber** [comment]
Was able to reproduce, and this change fixes the issue. :+1: 

FWIW, you can reproduce by downloading a JVM containing GraalVM from https://github.com/graalvm/graalvm-ce-builds/releases and placing it locally : `$HOME/.local/bin/openjdk1.8.0_272-jvmci-21.0-b03` . You can then run `JAVA_HOME=$HOME/.local/bin/openjdk1.8.0_272-jvmci-21.0-b03/ mvn clean verify -Pnative -DskipTests` . It should generate the binary in the target folder. You can then `xml.server.binary.path` and `xml.server.preferBinary` to use it.

**Comment by angelozerr** [comment]
Thanks a lot @rgrunber for your review and your great explanation :)

**Comment by JVimes** [comment]
The win32 binary from the GitHub artifacts fixed it for me. 👍

**Comment by angelozerr** [comment]
> The win32 binary from the GitHub artifacts fixed it for me. 

Great! Thanks for your feedback.

**Pull request merged**
